---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose
  namespace: sn-labs-thomasgarret  # Ensure the correct namespace
spec:
  workspaces:
    - name: source
  params:
    - name: args
      description: Arguments passed to nose
      type: string
      default: "-v"
  steps:
    - name: nosetests
      image: python:3.9-slim
      workingDir: /workspace/source
      script: |
        #!/bin/bash
        set -e
        python -m pip install --upgrade pip wheel
        pip install -r requirements.txt
        nosetests $(params.args)
